on:
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yaml'
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yaml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for OIDC authentication JWT
      contents: read # Required for checking out the repository
      pull-requests: write # Required for PR checks


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.SECRETS_ROLE_TO_ASSUME }} # Replace with your OIDC role ARN
          role-session-name: satyacorp-oidc # Unique session name
          aws-region: eu-west-2
          # Use OIDC authentication
          audience: sts.amazonaws.com #

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: terraform
