on:
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yaml'
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yaml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for OIDC authentication JWT
      contents: read # Required for checking out the repository
      pull-requests: write # Required for PR checks


    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Already using v4, which is good

      - name: Configure AWS credentials (OIDC)
        # --- CHANGE HERE: Update to v4 ---
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.SECRETS_ROLE_TO_ASSUME }} # I have set this in the repository secrets
          aws-region: eu-west-2 # AWS region to use
          role-session-name: GitHubActions # Name for the session
          audience: sts.amazonaws.com # Audience for OIDC authentication

      - name: Setup Terraform
        # --- CHANGE HERE: Ensure you're on the latest patch of v3, or consider v4 if available and compatible ---
        # As of my last update, v3 is still the latest major for setup-terraform.
        # Ensure your 'v3' tag pulls the latest patch.
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

      - name: Terraform destroy
        if: github.ref == 'refs/heads/main'
        run: terraform destroy -auto-approve
        working-directory: terraform